### PR TITLE
Install missing libpq-dev package

### LINKED ISSUE #63: Latest postgresql feature does not install libpq-dev
The latest release of the postgresql-client feature does not install `libpq-dev` anymore resulting in the Rails container to fail installing the `pg` gem.

A workaround until a fix is applied that worked for me... put this at the bottom of the Rails devcontainer Dockerfile:

```dockerfile
USER root
RUN apt-get update -y && apt-get -y install --no-install-recommends libpq-dev && rm -rf /var/lib/apt/lists/*
USER vscode
```

### PR DESCRIPTION
**Pull request by t27duck**
Closes #63

The latest postgresql-client feature no longer installs `libpq-dev` which is required for the `pg` gem install properly.

### CODE REVIEW

File: features/postgres-client/install.sh [hunk 1]
```diff
@@ -8,9 +8,9 @@ apt-get update -qq
 VERSION_EXISTS=$(apt-cache search --names-only postgresql-client-$POSTGRES_CLIENT_VERSION | wc -l)
 
 if [ "$VERSION_EXISTS" -ge 1 ]; then
-  apt-get install --no-install-recommends -y postgresql-client-$POSTGRES_CLIENT_VERSION
+  apt-get install --no-install-recommends -y libpq-dev postgresql-client-$POSTGRES_CLIENT_VERSION
 else
-  apt-get install --no-install-recommends -y postgresql-common
+  apt-get install --no-install-recommends -y postgresql-common libpq-dev
```
Comment (t27duck) [inline features/postgres-client/install.sh:13]: I fully concede I have no idea if this should be on this line or the one below it.

Comment (cubasepp) [reply features/postgres-client/install.sh:13]: You are right! Thank you for your fix. Sorry.
